class_name IconGen
## The app icon and the link-preview card, painted on the CPU from the game's own
## parts: PixelFont letterforms, LogoGen's chrome treatment and Palette ramps. They
## replace an externally generated PNG, because hard rule 1 says everything shipped
## is generated by code in this repo. tools/make_icons.tscn writes the files that
## build.sh hands to the web export; the game itself never calls this.
##
## Both pieces are drawn small on a pixel grid, then blown up by a whole-number
## factor with nearest sampling, so every size stays crisp pixel art and every
## colour is still a palette entry.

## Icon art is 32x32: 512 = x16, 180 = x5 and 144 = x4, both padded to size.
const ICON_GRID := 32
## Card art is 240x126; x5 gives 1200x630, the Open Graph / large-card size.
const CARD_GRID := Vector2i(240, 126)
const CARD_SCALE := 5


## Square icon, `size` px (32 or more). The art sits centred on the void colour.
static func icon(size: int) -> Image:
	var art := icon_art()
	var k := maxi(1, size / ICON_GRID)
	art.resize(ICON_GRID * k, ICON_GRID * k, Image.INTERPOLATE_NEAREST)
	var out := Image.create(size, size, false, Image.FORMAT_RGBA8)
	out.fill(void_color())
	var pad := (size - ICON_GRID * k) / 2
	out.blit_rect(art, Rect2i(Vector2i.ZERO, art.get_size()), Vector2i(pad, pad))
	return out


## The 32x32 master: the tunnel seen head-on (chamfered octagon rims receding into
## the dark), with the chrome V of VOID RUNNER in front of it.
static func icon_art() -> Image:
	var n := ICON_GRID
	var img := Image.create(n, n, false, Image.FORMAT_RGBA8)
	img.fill(void_color())
	var c := Vector2(n, n) * 0.5
	var rims := [
		[15.2, 13.8, Palette.ramp(Palette.CYAN, 13)],
		[10.6, 9.6, Palette.ramp(Palette.BLUE, 7)],
	]
	for y in n:
		for x in n:
			var r := _oct_radius(Vector2(x + 0.5, y + 0.5) - c, 1.0, 1.42)
			if r <= 3.4:
				img.set_pixel(x, y, Palette.ramp(Palette.VIOLET, 3))   # the far end
				continue
			for rim in rims:
				if r <= rim[0] and r > rim[1]:
					img.set_pixel(x, y, rim[2])
					break
	var v := v_mark()
	var used := v.get_used_rect()
	img.blend_rect(v, used, Vector2i(roundi(c.x - used.size.x * 0.5),
		roundi(c.y - used.size.y * 0.5) + 1))
	return img


## A true diagonal V with the title logo's chrome treatment. The 5x7 font's V has
## straight sides for five rows, so blown up this small it reads as a U.
static func v_mark() -> Image:
	const INK_W := 26
	const INK_H := 20
	const HALF := 2.0   # half the stroke width
	const EXTRUDE := 1
	var w := INK_W + EXTRUDE + 2
	var h := INK_H + EXTRUDE + 2
	var cx := 1.0 + INK_W * 0.5
	var apex := Vector2(cx, 1.0 + INK_H - HALF * 0.8)
	var tops := [Vector2(cx - (INK_W * 0.5 - HALF), 1.0), Vector2(cx + (INK_W * 0.5 - HALF), 1.0)]
	var mask := PackedByteArray()
	mask.resize(w * h)
	for y in range(1, 1 + INK_H):
		for x in w:
			var p := Vector2(x + 0.5, y + 0.5)
			for top in tops:
				if p.distance_to(Geometry2D.get_closest_point_to_segment(p, top, apex)) <= HALF:
					mask[y * w + x] = 1
					break
	return LogoGen.chrome_from_mask(mask, w, h, INK_H, EXTRUDE)


## 1200x630 link-preview card: the tunnel rushing at the viewer, and a DOS window
## with the chrome title, the tagline and what the game is.
static func card() -> Image:
	var img := card_art()
	img.resize(CARD_GRID.x * CARD_SCALE, CARD_GRID.y * CARD_SCALE, Image.INTERPOLATE_NEAREST)
	return img


static func card_art() -> Image:
	var g := CARD_GRID
	var img := Image.create(g.x, g.y, false, Image.FORMAT_RGBA8)
	img.fill(void_color())
	# the tunnel in perspective: rims at geometric depths, the nearest brightest.
	# Same 3:2 cross-section and light chamfer as the game's tunnels.
	var c := Vector2(g) * 0.5
	var rims: Array = []
	var s := 4.0
	while s < 260.0:
		rims.append(s)
		s *= 1.42
	for y in g.y:
		for x in g.x:
			var r := _oct_radius(Vector2(x + 0.5, y + 0.5) - c, 1.5, 1.7)
			for k in rims.size():
				var rs: float = rims[k]
				if r <= rs and r > rs - maxf(0.9, rs * 0.035):
					var depth := float(k) / float(rims.size() - 1)   # 0 far .. 1 near
					var col := Palette.ramp(Palette.BLUE, 3 + roundi(depth * 6.0)) \
						if depth < 0.5 else Palette.ramp(Palette.CYAN, 6 + roundi(depth * 7.0))
					img.set_pixel(x, y, col)
					break
	# a double-ruled DOS window, like the game's menus
	var win := Rect2i(10, 12, 220, 102)
	img.fill_rect(win, Palette.ramp(Palette.CYAN, 13))
	img.fill_rect(win.grow(-1), Palette.ramp(Palette.BLUE, 1))
	img.fill_rect(win.grow(-2), Palette.ramp(Palette.CYAN, 7))
	img.fill_rect(win.grow(-3), Palette.ramp(Palette.BLUE, 1))
	_text_centered(img, "BEYOND THE", 20, Palette.ramp(Palette.CYAN, 13))
	var logo := LogoGen.chrome_image("VOID RUNNER")
	var used := logo.get_used_rect()
	img.blend_rect(logo, used, Vector2i((g.x - used.size.x) / 2, 30))
	_text_centered(img, "RUN. SURVIVE. ESCAPE THE VOID.", 66, Palette.ramp(Palette.CYAN, 10))
	img.fill_rect(Rect2i(40, 79, 160, 1), Palette.ramp(Palette.CYAN, 5))
	_text_centered(img, "PLAY FREE IN YOUR BROWSER", 86, Palette.ramp(Palette.GOLD, 13))
	_text_centered(img, "KEYBOARD · MOUSE · GAMEPAD · TOUCH", 99, Palette.ramp(Palette.GREY, 9))
	return img


## The background every piece sits on: the darkest navy in the palette.
static func void_color() -> Color:
	return Palette.ramp(Palette.BLUE, 0)


## How far out `p` sits in octagon terms: the smallest half-height of an octagon
## (half-width = half-height x `aspect`, corners cut where |x|+|y| reaches
## `cut` x the half-height) that still contains it. Rims are bands of this value.
static func _oct_radius(p: Vector2, aspect: float, cut: float) -> float:
	var q := Vector2(absf(p.x) / aspect, absf(p.y))
	return maxf(maxf(q.x, q.y), (q.x + q.y) / cut)


static func _text_centered(img: Image, text: String, y: int, color: Color) -> void:
	var w := text.length() * PixelFont.ADVANCE - 1
	_text(img, text, Vector2i((img.get_width() - w) / 2, y), color)


## PixelFont's glyphs stamped 1:1 — the card's blow-up makes them chunky.
static func _text(img: Image, text: String, pos: Vector2i, color: Color) -> void:
	for i in text.length():
		var rows := PixelFont.glyph_rows(text[i])
		for ry in rows.size():
			for rx in rows[ry].length():
				if rows[ry][rx] == "#":
					var px := pos + Vector2i(i * PixelFont.ADVANCE + rx, ry)
					if px.x >= 0 and px.y >= 0 and px.x < img.get_width() and px.y < img.get_height():
						img.set_pixelv(px, color)
